# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: '1.0'
nodes:
  # --------------------  BGP (ASN, BGP Groups, BGP Sessions)  --------------------
  - name: AutonomousSystem
    namespace: Infra
    description: "An Autonomous System (AS) is a set of Internet routable IP prefixes belonging to a network"
    label: "Autonomous System"
    icon: "mdi:bank-circle-outline"
    default_filter: name__value
    human_friendly_id: ["name__value", "asn__value"]
    order_by: ["asn__value"]
    display_labels:
      - name__value
      - asn__value
    attributes:
      - name: name
        kind: Text
        unique: true
        order_weight: 1
      - name: asn
        kind: Number
        unique: true
        order_weight: 2
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: organization
        peer: OrganizationGeneric
        optional: false
        cardinality: one
        kind: Attribute
        order_weight: 3
  - name: BGPPeerGroup
    namespace: Infra
    description: "A BGP Peer Group is used to regroup parameters that are shared across multiple peers"
    label: "BGP Peer Group"
    icon: "mdi:view-grid-plus-outline"
    default_filter: name__value
    human_friendly_id: ["name__value"]
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
        order_weight: 1
      - name: description
        kind: Text
        optional: true
      - name: import_policies
        kind: Text
        optional: true
        order_weight: 4
      - name: export_policies
        kind: Text
        optional: true
        order_weight: 5
    relationships:
      - name: local_as
        identifier: bgppeergroup__local_as
        peer: InfraAutonomousSystem
        optional: true
        cardinality: one
        kind: Attribute
        order_weight: 2
      - name: remote_as
        identifier: bgppeergroup__remote_as
        peer: InfraAutonomousSystem
        optional: true
        cardinality: one
        kind: Attribute
        order_weight: 3
  - name: BGPSession
    namespace: Infra
    description: "A BGP Session represent a point to point connection between two routers"
    label: "BGP Session"
    icon: "mdi:router"
    inherit_from:
      - "CoreArtifactTarget"
    human_friendly_id: ["remote_as__asn__value", "remote_ip__address__value", "device__name__value"]
    order_by:
      - device__name__value
      - remote_as__asn__value
    attributes:
      - name: type
        kind: Text
        enum: [EXTERNAL, INTERNAL]
        order_weight: 1
      - name: description
        kind: Text
        optional: true
      - name: import_policies
        kind: Text
        optional: true
        order_weight: 8
      - name: export_policies
        kind: Text
        optional: true
        order_weight: 9
      - name: status
        kind: Dropdown
        order_weight: 6
        choices:
          - name: active
            label: Active
            description: "Fully operational and currently in service"
            color: "#7fbf7f"
          - name: provisioning
            label: Provisioning
            description: "In the process of being set up and configured"
            color: "#ffff7f"
          - name: maintenance
            label: Maintenance
            description: "Undergoing routine maintenance or repairs"
            color: "#ffd27f"
          - name: drained
            label: Drained
            description: "Temporarily taken out of service"
            color: "#bfbfbf"
      - name: role
        kind: Dropdown
        order_weight: 7
        choices:
          - name: backbone
            label: Backbone
            description: "Provide main data routes"
            color: "#6a5acd"
          - name: upstream
            label: Upstream
            description: "Connect to Internet service provider"
            color: "#9090de"
          - name: peering
            label: Peering
            description: "Connect with other networks via an IX"
            color: "#85db9b"
    relationships:
      - name: local_as
        identifier: bgpsession__local_as
        peer: InfraAutonomousSystem
        optional: true
        cardinality: one
        kind: Attribute
        order_weight: 2
      - name: remote_as
        identifier: bgpsession__remote_as
        peer: InfraAutonomousSystem
        optional: false
        cardinality: one
        kind: Attribute
        order_weight: 3
      - name: local_ip
        identifier: bgpsession__local_ip
        peer: BuiltinIPAddress
        optional: true
        cardinality: one
        kind: Attribute
        order_weight: 4
      - name: remote_ip
        identifier: bgpsession__remote_ip
        peer: BuiltinIPAddress
        optional: false
        cardinality: one
        kind: Attribute
        order_weight: 5
      - name: device
        peer: InfraDevice
        optional: false
        cardinality: one
      - name: peer_group
        peer: InfraBGPPeerGroup
        optional: true
        cardinality: one
        kind: Attribute
      - name: peer_session
        peer: InfraBGPSession
        optional: true
        cardinality: one
        kind: Attribute
